version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout

      - restore_cache:
          key: nuget-{{ checksum  "src/Circle/Circle.csproj" }}

      - run:
          name: Restore pacakges
          command:
            dotnet restore src/Circle

      - run:
          name: Install cake
          command:
            dotnet tool install -g cake.tool

      - run:
          name: Build app
          command: |
            ~/.dotnet/tools/dotnet-cake -target=Zip
            cp .publish/*.zip /tmp/circle-artifacts

      - save_cache:
          paths:
            - ~/.nuget/packages
          key: nuget-{{ checksum  "src/Circle/Circle.csproj" }}

      - store_artifacts:
          path: /tmp/circle-artifacts
          destination: circle.zip

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/circle-artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(date +%s)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/circle-artifacts

workflows:
  version: 2
  main:
    jobs:
      - build:
          # filters:
          #   tags:
          #     only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          # filters:
          #   branches:
          #     ignore: /.*/
          #   tags:
          #     only: /^\d+\.\d+\.\d+$/