version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout

      - restore_cache:
          key: nuget-{{ checksum  "src/Circle/Circle.csproj" }}

      - run:
          name: Restore pacakges
          command:
            dotnet restore src/Circle

      - run:
          name: Install cake
          command:
            dotnet tool install -g cake.tool

      - run:
          name: Build app
          command: |
            ~/.dotnet/tools/dotnet-cake -target=Zip

      - save_cache:
          paths:
            - ~/.nuget/packages
          key: nuget-{{ checksum  "src/Circle/Circle.csproj" }}

      - store_artifacts:
          path: .publish/*.zip