version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restore pacakges
          command:
            dotnet restore src/Circle
      - run:
          name: Install cake
          command:
            dotnet tool install -g cake.tool
      - run:
          name: Build app
          command: |
            ~/.dotnet/tools/dotnet-cake -target=Publish